# Site settings
title: Access to AI Conference
email: conference@accessto.io
url: http://accessto.io
description: "A conference for introducing professional programmers to machine learning and artificial intelligence."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: AccessTo Conference

social:
  - title: twitter
    url: https://twitter.com/AxsConf
  - title: github
    url: https://github.com/accessto
  - title: youtube
    url: https://www.youtube.com/channel/UCLJ_EZga09jTu13LFlrg97Q

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-2285755-9

# Build settings
markdown: kramdown
permalink: pretty
